### ISSUE TITLE
Get header CSS looking more like mockup

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/face-value#13]
I can help with some of the weird triangle stuff, if you like.

**Comment by sarahmonster** [comment]
Set up the triangle bit, and I can customize from there (otherwise I'd end up using an image).

**Comment by tofumatt** [comment]
Added the triangle in 5c7cc729b169434ad6fc129906849698e13348cb; feel free to tweak it as needed.

Once it's good you can close this issue, I think.
