### ISSUE TITLE
Make clearer which is the "home currency"

### ISSUE THREAD

**Issue by fwenzel** [tofumatt/face-value#21]
The idea is that one of the currencies is the "home currency" that you really don't change very often, and one is variable.

Perhaps on first startup, let people choose what their home currency is, then keep it around in localstorage?

On the other hand, the use case "I am interested in these two random currencies" shouldn't be prohibited either, even if neither is the currency you "think in".

**Comment by tofumatt** [comment]
I actually thought about a startup screen that asks you what your "Home currency" would be and I'm finally actually ready to implement it.

@sarahsemark: Think you have some time to wireframe something for a first-launch screen where the user could get a bit of education about the app and select their home currency?

That first screen would have the added benefit of giving the user something to do while the currencies are fetched are stored in the background for the first time.
