### ISSUE TITLE
GBP is completely the wrong value

### ISSUE THREAD

**Issue by sarahmonster** [tofumatt/face-value#33]
This threw me off so much when I first got to Bulgaria; I was convinced I'd accidentally taken out much more than I actually had! I'm not sure where the currency rate is coming from, but it's wrong unless that whole BBC scandal has bankrupted the UK economy. (Look at CAD to GBP and you'll see it thinks that a pound is worth $1.61!)

**Comment by tofumatt** [comment]
I screwed up the currency math for things but it works fine under certain circumstances. I'm aware of it though; gonna fix it tonight 

Matthew Riley MacPherson | http://lonelyvegan.com
(Sent from mobile)

**Comment by tofumatt** [comment]
Though, as a note: with the current conversion rate (as of November 28), 1GBP = $1.59CAD.
