### ISSUE TITLE
Create app icon

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/face-value#4]
We need an icon first, then we'll need specific iOS versions for home screen.

Some reference here: http://developer.apple.com/library/ios/#DOCUMENTATION/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by tofumatt** [comment]
Blocks #12

**Comment by sarahmonster** [comment]
SIZES!

**Comment by tofumatt** [comment]
57x57 px, which means 114x114 px for the retina version. We can leave the others out for now.

(For reference: [iOS App icon sizes](http://mrgan.tumblr.com/post/708404794/ios-app-icon-sizes))

**Comment by tofumatt** [comment]
Likely not needed for now, but here's Apple's spec for later: http://developer.apple.com/library/IOs/#documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

**Comment by tofumatt** [comment]
Temporary icons are here: c57380463b758261862858d9c99000630c13fec2
