### ISSUE TITLE
Indonesian Rupiahs is too big for the header

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/face-value#46]
Indonesian Rupiahs overflows the header and looks off. If "Rupiahs" works let's do that; otherwise we may need to scale this one down.

Maybe it's worth it to just scale all names like we do the values on coins/bills.

**Comment by sarahmonster** [comment]
"Rupiah" (no plural) makes sense here, given that there aren't any other currencies named as such and it's more commonly referred to without the "Indonesian...". 

Scaling names in that header will look _atrocious_. Let's avoid if possible.

**Comment by tofumatt** [comment]
I suppose now is a bad time to mention f9e53b34532c38d476df8e23e6ff9efbe17a6405 then.

OK, I'll fix up the Rupiah stuff and maybe change "Singapore Dollars" to "Sing. Dollars"? I really don't want to use symbols in the name in the header.

**Comment by tofumatt** [comment]
Fixed in 9d9bbba0d5ceefb4069c68bfa9338ab94651b392.
