### ISSUE TITLE
Create huge background image

### ISSUE THREAD

**Issue by tofumatt** [tofumatt/face-value#5]
We should just have a huge background image that will scale to at least iPad size at retina. The whole fixed positioning thing is tough once we have fixed elements as well, it seems.

**Comment by sarahmonster** [comment]
What dimensions does this need to be? (And how will it be positioned on smaller screens?)

**Comment by tofumatt** [comment]
I would think that going to a reasonable desktop retina size is fine (`960px@2x.png`)? Maybe after that the app should be centred on screen anyway, as any wider and it'll probably just look silly.

I'm OK with just an obscenely huge image -- 1024x2048? It should actually be 2048x4096, at retina size.

Is that too crazy?

**Comment by sarahmonster** [comment]
Trouble is that it doesn't look very good. I'm not sure how to deal with a background in a fully responsive way. I've added an image about as big as I can (and even the retina version is resized via Photoshop) without artificially inflating the size, but now it doesn't look as nice and is all centered and such. I'm not quite sure what the best solution is here, other than creating different backgrounds for different device sizes?

**Comment by tofumatt** [comment]
I'm entirely cool with different images based on device size, actually.

**Comment by tofumatt** [comment]
Oh, and we could center the image with `background` centring, no?

**Comment by sarahmonster** [comment]
Yes, but it looks nicer off-center and larger, especially on smaller devices where we can do such. Can we use the original background for devices 360x640 and smaller? (Larger devices look rather a mess right now anyway.)

**Comment by tofumatt** [comment]
Sure. Let's use the original, but let's say for 489px widths and smaller? That's the max width of the two-column layout, where I'm focusing on the design of the app currently anyway.
